%Displays a reference figure describing the subject folder layout the
%Report Generator expects, so a subject can be organized correctly
%before picking it in the folder browser.
function showRequiredFolderStructure()
structureText = { ...
    '<subject folder>/', ...
    '  IMAGING/', ...
    '    segmentation/               FreeSurfer recon-all output', ...
    '      mri/', ...
    '        orig.mgz                structural MRI', ...
    '      surf/', ...
    '        lh.pial                 left cortical surface mesh', ...
    '        rh.pial                 right cortical surface mesh', ...
    '      label/', ...
    '        lh.aparc.annot          left surface parcellation', ...
    '        rh.aparc.annot          right surface parcellation', ...
    '    Electrodes/', ...
    '      *.dat                     one file per electrode strip/grid,', ...
    '                                electrode coordinates in RAS space', ...
    '', ...
    'Legacy layout (also supported, used if present instead of', ...
    'IMAGING/segmentation/mri/orig.mgz):', ...
    '  IMAGING/NIfTI/MRI/*.img       structural MRI (Analyze format)', ...
    };

f = figure('Name','Expected Subject Folder Structure', ...
    'NumberTitle','off', ...
    'MenuBar','none', ...
    'Toolbar','none', ...
    'Units','pixels', ...
    'Position',[80 120 620 360], ...
    'Color','w');

uicontrol('Parent',f, ...
    'Style','edit', ...
    'Max',2,'Min',0, ...
    'Enable','inactive', ...
    'HorizontalAlignment','left', ...
    'FontName','Courier New', ...
    'FontSize',11, ...
    'Units','normalized', ...
    'Position',[0 0 1 1], ...
    'String',structureText, ...
    'BackgroundColor','w');
end
