function rptview(fileName, varargin)
%RPTVIEW displays a report generated by a DOM-based report generator.
%
%   RPTVIEW(RPT) displays the report RPT in a appropiate viewer. RPT is
%   an object of mlreportgen.dom.Document class.
%
%   RPTVIEW(RPT.OutputPath) displays the report RPT. It is equivalent to
%   RPTVIEW(RPT).
%
%   RPTVIEW(FILENAME.htmx) displays FILENAME.htmx in the MATLAB web browser.
%   RPTVIEW(FILENAME.zip) displays FILENAME.zip in the MATLAB web browser.
%   RPTVIEW(FILENAME.htmtx) displays FILENAME.htmtx in the MATLAB web browser.
%
%   RPTVIEW(FILENAME.html) displays FILENAME.html in the MATLAB web browser.
%   RPTVIEW(FILENAME.htmt) displays FILENAME.htmt in the MATLAB web browser.
%
%   RPTVIEW(FILENAME.docx) displays FILENAME.docx in Microsoft Word.
%   RPTVIEW(FILENAME.dotx) displays FILENAME.dotx in Microsoft Word.
%
%   RPTVIEW(FILENAME.pdf) displays FILENAME.pdf in a PDF viewer.
%   RPTVIEW(FILENAME.pdftx) displays FILENAME.pdftx in the MATLAB web browser.
%
%   RPTVIEW(FILENAME.docx, pdf) converts FILENAME.docx to PDF and
%   displays it in a PDF viewer.
%
%   RPTVIEW(RPTNAME, FORMAT) displays the version of RPTNAME specified by
%   FORMAT. Valid values for FORMAT are html, html-file, docx,  and pdf.
%   If a report and a template file with the same root name exist in the
%   directory, the report is displayed.
%
%   Example
%
%   Create a document in the current directory as follows:
%
%   import mlreportgen.dom.*
%   d = Document('myreport', 'docx');
%   append(d, 'Hello World');
%   close(d);
%
%   You may use any of the following function calls to open myreport.docx
%   in Microsoft Word.
%
%   rptview(d);
%   rptview(d.OutputPath);
%   rptview("myreport.docx");
%   rptview("myreport", "docx");

%   Copyright 2012-2018 MathWorks, Inc.
%--------1---------2---------3---------4---------5---------6---------7---------8

mlreportgen.utils.internal.rptview(fileName, varargin{:})
