function varargout = zipTemplate(templateFilename, varargin)
%ZIPTEMPLATE Package a DOM HTML template.
%   zipTemplate('ZIPPED_TEMPLATE_PATH', 'UNZIPPED_TEMPLATE_PATH',
%   'MAIN_DOCUMENT', 'PART_TEMPLATES') creates a compressed DOM template
%   file at the location specified by ZIPPED_TEMPLATE_PATH from the
%   unzipped template specified by UNZIPPED_TEMPLATE_PATH, including files
%   stored in subdirectories of the specified directory.  The resulting
%   compressed template preserves the directory structure of the
%   uncompressed template. The unzipped directory must contain a main
%   document name MAIN_DOCUMENT.html where MAIN_DOCUMENT is the root name
%   of the file, e.g., report.html. It must also contain a document part
%   template library file named PART_TEMPLATES.html, where PART_TEMPLATES
%   is the root name of the file, e.g., docpart_templates.html.
%
%   The zipped template file contains metafiles generated by this command
%   that enable the DOM API to determine the location of the template's
%   main document and document part template library.
% 
%   The command optionally can include metadata that defines the location
%   of the template's image directory. To enable this option include a text
%   file named _imgprefix in the unzipped template's images directory. The
%   _imgprefix may optionally include a prefix to be used by the DOM to
%   generate the names of images appended to documents based on the
%   template. For example, if the _imgprefix file contains the prefix
%   image, the DOM API generates image names of the form imageN.ext, e.g.,
%   image1.png, image2.png, etc. If the _imgprefix file is empty, the
%   generated metadata specifies the image prefix to be image.
%
%   The DOM API assumes by default that images are located in a
%   subdirectory named images of the template's root directory. Thus, you
%   do not need to include an _imgprefix file in an unzipped template whose
%   image directory is named TEMPLATE_ROOT/images.
%   
%   zipTemplate('ZIPPED_TEMPLATE_PATH', 'UNZIPPED_TEMPLATE_PATH',
%   'MAIN_DOCUMENT') assumes that the name of the document part template
%   library, if present in the unzipped template, is
%   docpart_templates.html.
%   
%   zipTemplate('ZIPPED_TEMPLATE_PATH', 'UNZIPPED_TEMPLATE_PATH') 
%   assumes that the name of the main document file is report.html. A file
%   of that name must be present in the unzipped template.
%   
%   zipTemplate('TEMPLATE_PATH') creates a compressed DOM template file.
%   The TEMPLATE_PATH argument may specify the path of the uncompressed
%   template directory or the path of the resulting template file including
%   its extension. If TEMPLATE_PATH specifies a directory, the resulting
%   template has the path TEMPLATE_PATH.htmtx. If TEMPLATE_PATH ends in an
%   extension (e.g., mytemplate.zip), the resulting compressed template has
%   the specified extension and the uncompressed template is assumed to
%   reside in a directory specified by TEMPLATE_PATH minus the extenion,
%   e.g., mytemplate).
%
%   Examples
%   --------
%   zipTemplate('myTemplate');
%   zipTemplate('myTemplate.htmtx');
%   zipTemplate('myTemplate.htmtx', 'myTemplate', ...
%        'mainpart.html', 'documentpart_templates.html');
%
%   See also unzipTemplate

%   Copyright 2014-2016 The MathWorks, Inc.

varargout{:} = rptgen.zipTemplate(templateFilename, varargin{:});