%mlreportgen.dom.TOC Creates a table of contents
%    toc = TOC() creates a table of contents up to outline level 3 with the
%    leader pattern as dots ('.').
%
%    toc = TOC(level) creates a table of contents up to the specified 
%    outline level with the leader pattern as dots ('.').
%
%    toc = TOC(level, pattern) creates a table of contents up to the 
%    specified outline level with the specified leader pattern.
%
%    TOC methods:
%        clone              - Clone this TOC object
%
%    TOC properties:
%        NumberOfLevels     - Outline level number
%        LeaderPattern      - Leader pattern
%        StyleName          - Name of TOC object's style sheet-defined style
%        Style              - Formats that define this TOC object's style
%        CustomAttributes   - Custom element attributes
%        Children           - Children of this TOC object
%        Parent             - Parent of this TOC object
%        Tag                - Tag of this TOC object
%        Id                 - Id for this TOC object
%
%    Customize Format of TOC Entries
%
%    Styles in a document's template determine the size, spacing, color, and
%    other format properties of the entries in a table of contents
%    generated by this object. The mlreportgen.dom.Document object's
%    default Word and PDF templates define styles that determine the default
%    format of TOC entries. The styles are named TOC1, TOC2, ... TOC6,
%    where style TOC1 defines the format of level 1 entries, style TOC2
%    defines the format of level 2 entries, etc. To change the format of
%    the entries, create a custom document template that redefines these
%    styles and use the template to generate your document. Note that you
%    must redefine the styles in the document template, not in the template
%    used by a document part that contains this TOC object.

%    Copyright 2015-2018 MathWorks, Inc.
%    Built-in class

%{
properties
    
     %NumberOfLevels Outline level number 
     %    This property specifies the outline level number up to which the 
     %    table of contents needs to be generated.
     %
     %    Valid values are 1 to 9.
     NumberOfLevels;

     %LeaderPattern Leader pattern
     %    This property specifies the leader pattern to be used in the 
     %    table of contents.
     %
     %    Valid values are:
     %
     %    Value               DESCRIPTION
     %    'dots' or '.'       leader of dots
     %    'space' or ' '      leader of spaces
     LeaderPattern;

end
%}