%mlreportgen.dom.AutoNumber An automatically generated number
%    autoObj = AutoNumber() creates an auto number having an unspecified
%    auto number stream.
%
%    autoObj = AutoNumber('stream') creates an auto number whose value is
%    generated by the specified auto number stream. If the stream does 
%    not exist, the DOM creates an Arabic number stream having the 
%    specified name with an initial value of 0. If you want to
%    use a stream with other properties (e.g., roman numerals), you must
%    create a stream with the desired properties explicitly
%    (see mlreportgen.dom.Document.createAutoNumberStream);
%
%    autoObj = AutoNumber('stream', 'stylename') creates an auto number 
%    generated by the specified auto number stream and having the 
%    specified style name. The style must be defined in the stylesheet of 
%    the template of the document to which this auto number object is 
%    appended.
%
%    AutoNumber methods:
%        append         - Append a custom element to this auto number object
%        clone          - Clone this auto number object
%
%    AutoNumber properties:
%        BackgroundColor   - Background color of this auto number
%        Bold              - Whether this auto number is bold
%        Color             - Color of this auto number
%        CustomAttributes  - Custom element attributes
%        FontFamilyName    - Name of font family used to render this auto number
%        FontSize          - Size of font used to render this auto number
%        Id                - Id of this auto number
%        Italic            - Whether this auto number is italic
%        Style             - Formats that define this auto number's style
%        StreamName        - Name of number stream that generates this number
%        Strike            - Type of strikethrough to draw through auto number
%        StyleName         - Name of this auto numbers's stylesheet-defined style
%        Tag               - Tag of this auto number
%        Underline         - Type of line, if any, to draw under this auto number
%        WhiteSpace        - Preserves white space and line breaks in auto number
%
%    Example:
%    
%    import mlreportgen.dom.*;
%    doctype = 'html';
%    d = Document('test', doctype);
%    
%    p = Paragraph('Chapter ');
%    p.Style = { CounterInc('chapter'), CounterReset('table'), WhiteSpace('preserve') };
%    append(p, AutoNumber('chapter'));
%    append(d, p);
%    
%    p = Paragraph('Table ');
%    append(p, AutoNumber('chapter'));
%    append(p, '.');
%    append(p, AutoNumber('table'));
%    p.Style = { CounterInc('table'), WhiteSpace('preserve') };
%    append(d, p);
%    
%    p = Paragraph('Chapter ');
%    p.Style = { CounterInc('chapter'), CounterReset('table'), WhiteSpace('preserve') };
%    append(p, AutoNumber('chapter'));
%    append(d, p);
%    
%    p = Paragraph('Table ');
%    append(p, AutoNumber('chapter'));
%    append(p, '.');
%    append(p, AutoNumber('table'));
%    p.Style = { CounterInc('table'), WhiteSpace('preserve') };
%    append(d, p);
%    
%    close(d);
%    rptview('test', doctype);
%    
%    See also mlreportgen.dom.Document.createAutoNumberStream,
%    mlreportgen.dom.Document.getAutoNumberStream,
%    mlreportgen.dom.CounterInc, mlreportgen.dom.CounterReset

%    Copyright 2014-2017 Mathworks, Inc.
%    Built-in class

%{
properties
     %StreamName Name of auto number stream
     %    Name of auto number stream that generates the value of this
     %    instance of an auto number.
     %
     %    See also mlreportgen.dom.Document.createAutoNumberStream
     StreamName;

     %BackgroundColor Background color of this auto number
     %    You may specify the background color either as a color
     %    name (e.g., 'red') or a hexadecimal RGB value of the form
     %    '#rrggbb', e.g., 'FF0000'. If this property is empty and the 
     %    auto number’s StyleName property specifies a style sheet style, the 
     %    color of this auto number is determined by the specified style. 
     %
     %    Note: Setting this property adds a corresponding BackgroundColor 
     %    format object to this auto number’s Style property. Unsetting this 
     %    property removes the object.
     %
     BackgroundColor;

     %Bold Whether this auto number is bold
     %    If true, this property cause this auto number to be rendered bold.
     %    If this property is false, the auto number is rendered normal weight. 
     %    If this property is empty and the auto number’s StyleName property
     %    specifies a stylesheet style, the weight of this auto number is 
     %    determined by the specified style.
     %
     %    Note: Setting this property adds a corresponding Bold 
     %    format object to this auto number’s Style property. Unsetting this 
     %    property removes the object.
     %
     Bold;

     %Color Color of this auto number
     %    Color of this auto number. You may specify the color either as a color
     %    name (e.g., 'red') or a hexadecimal RGB value of the form
     %    '#rrggbb', e.g., 'FF0000'. If this property is empty and the 
     %    auto number’s StyleName property specifies a style sheet style, the 
     %    color of this auto number is determined by the specified style.
     %
     %    Note: Setting this property adds a corresponding Color 
     %    format object to this auto number’s Style property. Unsetting this 
     %    property removes the object.
     %
     Color;

     %Content String content of this auto number object
     %     Text string contained by this auto number object.
     Content;

     %FontFamilyName Name of font family to be used to render this auto number.
     %    If you need to specify substitutions for this font, do not set 
     %    this property. Instead create and add a FontFamily object to 
     %    this auto number's Style property.
     %
     %    Note: Setting this property adds a corresponding FontFamily 
     %    format object to this auto number's Style property. Unsetting this 
     %    property removes the object.
     FontFamilyName;

     %FontSize Size of font to be used to render this auto number.
     %
     %    The value of this property is a string having the format 
     %    valueUnits where Units is an abbreviation for the units in
     %    which the size is expressed. The following abbreviations are
     %    valid:
     %
     %    Abbreviation  Units
     %
     %    px            pixels
     %    cm            centimeters
     %    in            inches
     %    mm            millimeters
     %    pc            picas
     %    pt            points
     %
     %
     %    Note: Setting this property adds a corresponding FontSize format
     %    object to this auto number's Style property. Unsetting this property
     %    removes the object.
     FontSize;

     %Italic Whether this auto number is italic
     %    If true, this property cause this auto number to be rendered italic.
     %    If this property is false, the auto number is rendered upright. 
     %    If this property is empty and the auto number’s StyleName property
     %    specifies a stylesheet style, the slant of this auto number is 
     %    determined by the specified style.
     %
     %    Note: Setting this property adds a corresponding Italic 
     %    format object to this auto number’s Style property. Unsetting this 
     %    property removes the object.
     %
     Italic;

     %Strike Type of strikethrough, if any, to draw through this auto number.
     %    Valid types are:
     %
     %                                                  Applies To
     %    Valid Value      Description                  DOCX    HTML
     %    'double'         Double line                    X       
     %    'none'           Do not draw a strikethrough    X       X	 
     %    'single'         Single line                    X       X
     %
     %    Note: Setting this property adds a corresponding Strike format 
     %    object to this auto number's Style property. Unsetting this property
     %    removes the object.
     Strike;

     %Underline Type of line, if any, to draw under this auto number
     %    Type of line, if any, to draw under this auto number. For HTML output, 
     %    the only valid values for this property are 'single' and 'none'.  
     %    In addition to these types, DOCX output supports an extensive 
     %    array of other underline types: 
     %
     %    Valid Value        Description
     %
     %    single             Single underline
     %    words              Underline non-space characters only
     %    double             Double underline
     %    thick              Thick underline
     %    dotted             Dotted underline
     %    dottedHeavy        Thick dotted underline
     %    dash               Dashed underline
     %    dashedHeavy        Thick dashed underline
     %    dashLong           Long dashed underline
     %    dashLongHeavy		 Thick long dashed underline
     %    dotDash		     Dash-dot underline
     %    dashDotHeavy		 Thick dash-dot underline
     %    dotDotDash         Dash-dot-dot underline
     %    dashDotDotHeavy    Thick dash-dot-dot underline
     %    wave               Wavy underline
     %    wavyHeavy          Heavy wavy underline
     %    wavyDouble         Double wavy underline
     %    none               No underline
     %
     %    If this property is empty and the auto number’s StyleName property 
     %    specifies a style sheet style, the line drawn under this auto number, 
     %    if any, is determined by the specified style. 
     %
     %    If you want to specify the color as well as the type of the
     %    underline, do not set this property, Instead, set this auto number’s
     %    Style property to include an Underline format object that 
     %    specifies the desired type and color.
     %
     %    Note: Setting this property adds a corresponding Underline 
     %    format object to this auto number’s Style property. Unsetting this 
     %    property removes the object.
     Underline;

     %Preserves white space and line breaks in auto number.
     %
     %                                                    Applies To
     %    Valid Value   Description	                       DOCX HTML
	 %	
     %    'normal'      Do not preserve white space and      X    X
     %                  line breaks in auto number	 	 
     %    'nowrap'      Sequences of white space collapse         X
     %                  into a single whitespace. Text never
     %                  wraps to the next line.  		 
     %    'pre'         Preserves white space. Text wraps         X
     %                  only on line breaks Acts like the
     %                  <pre> tag in HTML.		 
     %    'pre-line'    Sequences of white space                  X
     %                  collapse into a single white space.
     %                  Text wraps when necessary and on
     %                  line breaks.		 
     %    'pre-wrap'    Preserves white space. Text wraps         X
     %                  when necessary and on line breaks     X   X		 
     %    'preserve'    Same as pre. This  is the only
     %                  option that works in the MATLAB 
     %                  browser. For HTML output, this option
     %                  wraps the auto number content of a Text
     %                  object in HTML pre tags. If the auto number
     %                  contains line feeds, the option wraps
     %                  each line of auto number in a pre element
     %                  followed by a <br/> element. This is
     %                  done to ensure that the HTML output
     %                  is also valid XML and hence can be
     %                  parsed by an XML parser for
     %                  verification purposes.	 	 
     %
     %     Note: Setting this property adds a corresponding WhiteSpace 
     %     format object to this auto number’s Style property. Unsetting this 
     %     property removes the object.
     WhiteSpace;

end
%}